// Program 1

import fetch from 'node-fetch'

const cekUser = (email) => {
    return new Promise((resolve, reject) => {
        setTimeout( async () => {
            const data = await fetch('https://jsonplaceholder.typicode.com/users')
            const data2 = await data.json()
            const data3 = data2.map((item) => {return (item.email)})
            let cek = data3.find((item) => item == email)

            if (cek) {
                resolve (email)
            } else {
                reject('email yang dimasukkan salah')
            }
    
        }, 3000)
    })
}

const cekEmail = async (param) => {
    try {
        const result = await cekUser(param)
            console.log (result)
        } catch (error) {
            console.log (error)
        } finally {
            console.log('Proses telah selesai')
        }
    }

cekEmail('annisadzakia@gmail.com')
cekEmail('Karley_Dach@jasper.info')

// cekUser('Karley_Dach@jasper.info').then((result) => {
//     console.log (result)
// }).catch((error) => {
//     console.log(error)
// }).finally(()=> {
//     console.log('Proses telah selesai')
// })


// Program 2

const cekUser2 = (password) => {
    return new Promise((resolve, reject) => {
        setTimeout( async () => {
            const data = await fetch('https://jsonplaceholder.typicode.com/users')
            const data2 = await data.json()
            const data3 = data2.map(({address}) => {return (address.zipcode)})
            let cek = data3.find((item) => item == password)

            if (cek) {
                resolve ('login berhasil!')
            } else {
                reject('password yang dimasukkan salah')
            }
    
        }, 3000)
    })
}

const cekPassword = async (param) => {
    try {
        const result = await cekUser2(param)
            console.log (result)
        } catch (error) {
            console.log (error)
        } finally {
            console.log('Proses telah selesai')
        }
    }

cekPassword('123456')
cekPassword('58804-1099')


// cekUser2('59590-4157').then((result) => {
//     console.log (result)
// }).catch((error) => {
//     console.log(error)
// }).finally(()=> {
//     console.log('Proses telah selesai')
// })
